### sign-up
POST   http://localhost:8080/auth/sign-up
Content-Type: application/json

{
	"name": "Den",
	"username": "KoLLlaka",
	"password": "qwerty"
}

### sign-in
POST   http://localhost:8080/auth/sign-in
Content-Type: application/json

{
	"username": "KoLLlaka",
	"password": "qwerty"
}

### api/lists/
POST   http://localhost:8080/api/lists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDg2ODMyNTQsImlhdCI6MTY0ODY0MDA1NCwidXNlcl9pZCI6Nn0.cUBbswUaSnDPUSmG5DelpFAm6E_6By8r3PG_c-4ojCM

{}

###
GET    http://localhost:8080/api/lists/
Content-Type: application/json

{}

###
GET    http://localhost:8080/api/lists/:id
Content-Type: application/json

{}

###
PUT    http://localhost:8080/api/lists/:id
Content-Type: application/json

{}

###
DELETE http://localhost:8080/api/lists/:id
Content-Type: application/json

{}

###
POST   http://localhost:8080/api/lists/:id/items/
Content-Type: application/json

{}

###
GET    http://localhost:8080/api/lists/:id/items/
Content-Type: application/json

{}

###
GET    http://localhost:8080/api/lists/:id/items/:item_id
Content-Type: application/json

{}

###
PUT    http://localhost:8080/api/lists/:id/items/:item_id
Content-Type: application/json

{}

###
DELETE http://localhost:8080/api/lists/:id/items/:item_id
Content-Type: application/json

{}