### sign-up
POST   http://localhost:8080/auth/sign-up
Content-Type: application/json

{
	"name": "Den",
	"username": "KoLLlaka",
	"password": "qwerty"
}

### sign-in
POST   http://localhost:8080/auth/sign-in
Content-Type: application/json

{
	"username": "KoLLlaka",
	"password": "qwerty"
}

### api/lists/ POST
POST   http://localhost:8080/api/lists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDg2OTQyNzEsImlhdCI6MTY0ODY1MTA3MSwidXNlcl9pZCI6Nn0.Kba_3S9YXaTvGMFrJnYIrzIc0PAlSxasd6YtIEl4D2I

{
	"title": "list 2",
	"description": "desc to list 2"
}

### api/lists/ GET
GET    http://localhost:8080/api/lists/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDg3MDA0NDYsImlhdCI6MTY0ODY1NzI0NiwidXNlcl9pZCI6Nn0.kQ2djfFB12IeJX85GPabyzqHl4nyrx_w_84hiSuyV-I

{}

### api/lists/:id GET
GET    http://localhost:8080/api/lists/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDg3MDA0NDYsImlhdCI6MTY0ODY1NzI0NiwidXNlcl9pZCI6Nn0.kQ2djfFB12IeJX85GPabyzqHl4nyrx_w_84hiSuyV-I

{}

###
PUT    http://localhost:8080/api/lists/:id
Content-Type: application/json
Authorization: Bearer

{}

###
DELETE http://localhost:8080/api/lists/:id
Content-Type: application/json
Authorization: Bearer

{}

###
POST   http://localhost:8080/api/lists/:id/items/
Content-Type: application/json
Authorization: Bearer

{}

###
GET    http://localhost:8080/api/lists/:id/items/
Content-Type: application/json
Authorization: Bearer

{}

###
GET    http://localhost:8080/api/lists/:id/items/:item_id
Content-Type: application/json
Authorization: Bearer

{}

###
PUT    http://localhost:8080/api/lists/:id/items/:item_id
Content-Type: application/json
Authorization: Bearer

{}

###
DELETE http://localhost:8080/api/lists/:id/items/:item_id
Content-Type: application/json
Authorization: Bearer

{}